# This is a generated file. Not intended for manual editing.
services:
  geo-resolver:
    build:
      context: "/Users/vol.inc/Projects/Own/geo-resolver"
      dockerfile: "GeoResolver/Dockerfile"
      target: "final"
    # Use ENTRYPOINT and CMD from the Dockerfile (./GeoResolver in final stage)
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "georesolver:dev"
    ports: []
