# This is a generated file. Not intended for manual editing.
services:
  geo-resolver:
    build:
      context: "/Users/vol.inc/Projects/Own/geo-resolver"
      dockerfile: "GeoResolver/Dockerfile"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net10.0/GeoResolver.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "georesolver:dev"
    ports: []
    volumes:
    - "/Users/vol.inc/Projects/Own/geo-resolver/GeoResolver:/app:rw"
    - "/Users/vol.inc/Projects/Own/geo-resolver:/src:rw"
    - "/Users/vol.inc/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
